name: 2. Demo Playwright workflow with Allure report

on:
  workflow_dispatch: 
    inputs:
      TAG_NAME:
        description: 'Enter tag name to run test cases:'
        required: true
        default: 'smoke'
      ENV_NAME:
        description: 'Select the environment:'
        type: choice
        required: true
        options:
          - DEV
          - QA
          - PROD      

jobs:
  test_summary:
    runs-on: ubuntu-latest
    steps:
      - name: Test Run Summary
        run: |
          echo "Actor: ${{ github.actor }}"
          echo "Branch: ${{ github.ref_name }}"
          echo "Action_repository: ${{ github.action_repository }}"
          echo "BDD Tags: @${{ github.event.inputs.TAG_NAME }}"
          echo "Run ENV: ${{ github.event.inputs.ENV_NAME }}"

  regression_test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    needs: test_summary
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - run: npm run build --if-present

      - name: install playwright browsers
        run: npx playwright install --with-deps

      # # Setup Xvfb to run headless mode
      # - run: sudo apt-get install xvfb

      # # Run test cases with X virtual framebuffer (Xvfb)
      # - name: Run Playwright tests
      #   run: xvfb-run --auto-servernum --server-num=1 --server-args='-screen 0, 1920x1080x24' npx playwright test

      - run: npx playwright test

      # Load source code to get Allure results
      - name: Load test report history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      # - uses: actions/upload-artifact@v3
      #   if: always()
      #   with:
      #     name: allure-results
      #     path: allure-results

      - name: configure allure using allure report action
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history
          
      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history
